import { Contract, Employee, DemandLog, AreaResponsavel, TrabalhistaEnvio } from '../types/index.ts';

export const INITIAL_AREAS: AreaResponsavel[] = [
  {
    id: 'area-01',
    nome: 'Logística & Centros de Distribuição (CDs)',
    responsavelNome: 'Ricardo Fontes Silveira',
    responsavelCargo: 'Gerente Executivo de Operações Logísticas',
    responsavelEmail: 'ricardo.fontes@gpa.com.br',
    responsavelTelefone: '(11) 98765-4321',
    unidadeOuLoja: 'CD Central Osasco / SP',
    observacoes: 'Monitoramento contínuo de operadores de empilhadeira, motoristas e ajudantes de carga.',
  },
  {
    id: 'area-02',
    nome: 'Manutenção Predial & Obras',
    responsavelNome: 'Mariana Duarte Prado',
    responsavelCargo: 'Coordenadora de Engenharia & Manutenção',
    responsavelEmail: 'mariana.prado@gpa.com.br',
    responsavelTelefone: '(11) 97654-1122',
    unidadeOuLoja: 'Regional São Paulo Capital',
    observacoes: 'Controle de NR-10 (Elétrica), NR-35 (Altura) e fichas de EPI para equipes terceirizadas.',
  },
  {
    id: 'area-03',
    nome: 'Prevenção de Perdas & Segurança Patrimonial',
    responsavelNome: 'Carlos Alberto Tavares',
    responsavelCargo: 'Supervisor de Segurança e Prevenção',
    responsavelEmail: 'carlos.tavares@gpa.com.br',
    responsavelTelefone: '(11) 99882-3344',
    unidadeOuLoja: 'Lojas Pão de Açúcar & Minuto',
    observacoes: 'Fiscalização de vigilância armada/desarmada e controle de acessos às portarias.',
  },
  {
    id: 'area-04',
    nome: 'Facilities, Limpeza & Higienização',
    responsavelNome: 'Juliana Beatriz Neves',
    responsavelCargo: 'Gerente de Facilities & Terceiros',
    responsavelEmail: 'juliana.neves@gpa.com.br',
    responsavelTelefone: '(11) 99123-5566',
    unidadeOuLoja: 'Edifício Sede GPA - Brig. Luís Antônio',
    observacoes: 'Acompanhamento rigoroso de ASO admissional/periódico e treinamento de químicos.',
  },
  {
    id: 'area-05',
    nome: 'Operações de Loja & Perecíveis',
    responsavelNome: 'Fernando Henrique Lemos',
    responsavelCargo: 'Gerente Regional de Operações',
    responsavelEmail: 'fernando.lemos@gpa.com.br',
    responsavelTelefone: '(11) 98234-7788',
    unidadeOuLoja: 'Hiper & Supermercados GPA',
    observacoes: 'Controle de exames específicos para manipuladores de alimentos e câmaras frigoríficas.',
  },
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'ctr-4600001229',
    numero: '4600001229',
    titulo: 'PRESTAÇÃO DE SERVIÇOS DE CONTROLE DE ACESSO ÀS ÁREAS RESTRITAS DE SEGURANÇA',
    objeto: 'PRESTAÇÃO DE SERVIÇOS DE CONTROLE DE ACESSO ÀS ÁREAS RESTRITAS DE SEGURANÇA',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: '',
    cliente: 'Concessionária Aeroporto Internacional',
    unidade: 'Áreas Restritas de Segurança (ARS)',
    gestorResponsavel: 'Coordenação de Segurança Aeroportuária',
    emailContato: 'seguranca.aeroporto@orbital.com.br',
    telefoneContato: '(11) 2445-1000',
    dataInicio: '01/10/2017',
    dataTermino: '31/03/2021',
    vigenciaInicio: '2017-10-01',
    vigenciaFim: '2021-03-31',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
    observacoes: 'Contrato concluído com regularidade documental validada ao término.',
    documentosContrato: [
      { id: 'doc-1', nome: 'Contrato Social e Procuração', tipo: 'Jurídico', status: 'Validado', dataUpload: '01/10/2017' },
      { id: 'doc-2', nome: 'Apólice de Seguro de Responsabilidade Civil', tipo: 'Seguros', status: 'Validado', dataUpload: '01/10/2017' },
      { id: 'doc-3', nome: 'PGR e PCMSO do Contrato', tipo: 'SST', status: 'Validado', dataUpload: '01/10/2017' },
      { id: 'doc-4', nome: 'Certidão Negativa de Débitos Trabalhistas (CNDT)', tipo: 'Trabalhista', status: 'Validado', dataUpload: '15/03/2021' },
    ],
  },
  {
    id: 'ctr-GRU020320180103',
    numero: 'GRU020320180103',
    titulo: 'Área destinada a escritório operacional',
    objeto: 'Área destinada a escritório operacional',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Terminal de Cargas / Edifício Operacional',
    gestorResponsavel: 'Gerência de Operações de Solo',
    dataInicio: '01/12/2018',
    dataTermino: '30/11/2021',
    vigenciaInicio: '2018-12-01',
    vigenciaFim: '2021-11-30',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
    documentosContrato: [
      { id: 'doc-103-1', nome: 'Alvará de Funcionamento e Licença', tipo: 'Regulatório', status: 'Validado' },
      { id: 'doc-103-2', nome: 'Laudo AVCB das Instalações', tipo: 'Predial', status: 'Validado' },
    ],
  },
  {
    id: 'ctr-GRU020320180104',
    numero: 'GRU020320180104',
    titulo: 'Área destinada a Vestiário (Guarda Volumes)',
    objeto: 'Área destinada a Vestiário (Guarda Volumes)',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Terminal Operacional',
    gestorResponsavel: 'Gestão de Espaços e Facilities',
    dataInicio: '01/12/2018',
    dataTermino: '30/11/2021',
    vigenciaInicio: '2018-12-01',
    vigenciaFim: '2021-11-30',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
    documentosContrato: [
      { id: 'doc-104-1', nome: 'Laudo de Higienização e Sanitização', tipo: 'SST/Sanitário', status: 'Validado' },
      { id: 'doc-104-2', nome: 'Seguro do Espaço Físico', tipo: 'Seguros', status: 'Validado' },
    ],
  },
  {
    id: 'ctr-GRU020320200072',
    numero: 'GRU020320200072',
    titulo: 'Área destinada para realização da atividade de guarda e controle de bagagens com antecedência para voos internacionais',
    objeto: 'Área destinada para realização da atividade de guarda e controle de bagagens com antecedência para voos internacionais',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Terminal 3 - Internacional',
    gestorResponsavel: 'Supervisão de Operações Internacionais',
    emailContato: 'bagagens.internacional@orbital.com.br',
    telefoneContato: '(11) 2445-2233',
    dataInicio: '01/10/2020',
    dataTermino: '30/11/2026',
    vigenciaInicio: '2020-10-01',
    vigenciaFim: '2026-11-30',
    statusVigencia: 'Vigente',
    statusDocumentos: 'Em Análise',
    status: 'ATIVO',
    limiteBloqueioConformidade: 85,
    observacoes: 'Documentação de renovação periódica enviada e em análise pela auditoria.',
    documentosContrato: [
      { id: 'doc-72-1', nome: 'Certificado de Homologação ANAC / AVSEC', tipo: 'Regulatório', status: 'Validado' },
      { id: 'doc-72-2', nome: 'Apólice de Seguro de Cargas e Bagagens', tipo: 'Seguros', status: 'Em Análise', motivoReprovacao: 'Aguardando validação do endosso pela seguradora' },
      { id: 'doc-72-3', nome: 'PGR / PCMSO Específico Guarda Internacional', tipo: 'SST', status: 'Validado' },
      { id: 'doc-72-4', nome: 'Certidões Negativas Tributárias e Trabalhistas', tipo: 'Fiscal/Trabalhista', status: 'Validado' },
    ],
  },
  {
    id: 'ctr-GRU020320180112',
    numero: 'GRU020320180112',
    titulo: 'Área destinada a estacionamento e guarda de equipamentos.',
    objeto: 'Área destinada a estacionamento e guarda de equipamentos.',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Pátio de Aeronaves / GSE',
    gestorResponsavel: 'Gestão de GSE e Equipamentos de Pátio',
    dataInicio: '01/12/2018',
    dataTermino: '30/11/2021',
    vigenciaInicio: '2018-12-01',
    vigenciaFim: '2021-11-30',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
  },
  {
    id: 'ctr-GRU020320180111',
    numero: 'GRU020320180111',
    titulo: 'Área destinada a escritório operacional',
    objeto: 'Área destinada a escritório operacional',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Terminal 2',
    gestorResponsavel: 'Supervisão de Turno',
    dataInicio: '01/12/2018',
    dataTermino: '30/11/2021',
    vigenciaInicio: '2018-12-01',
    vigenciaFim: '2021-11-30',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
  },
  {
    id: 'ctr-GRU020320180110',
    numero: 'GRU020320180110',
    titulo: 'Área destinada a estacionamento e guarda de equipamentos.',
    objeto: 'Área destinada a estacionamento e guarda de equipamentos.',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Pátio Remoto',
    gestorResponsavel: 'Gestão de GSE',
    dataInicio: '01/12/2018',
    dataTermino: '30/11/2021',
    vigenciaInicio: '2018-12-01',
    vigenciaFim: '2021-11-30',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
  },
  {
    id: 'ctr-GRU020320180109',
    numero: 'GRU020320180109',
    titulo: 'Área destinada a carga de baterias',
    objeto: 'Área destinada a carga de baterias',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Oficina Central GSE',
    gestorResponsavel: 'Engenharia de Manutenção Elétrica',
    dataInicio: '01/12/2018',
    dataTermino: '30/11/2021',
    vigenciaInicio: '2018-12-01',
    vigenciaFim: '2021-11-30',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
  },
  {
    id: 'ctr-GRU020320140109',
    numero: 'GRU020320140109',
    titulo: 'Área destinada para realização de atividade de prestação de serviços de inspeção de bagagens despachadas Internacionais e Domésticas dos Terminais 1,2 e 3 às companhias aéreas e manuseio de bagagens nos sistemas de inspeção com o objetivo de atender as exigências do sistema de proteção da Aviação Civil e DAVSEC nº 04-21.; ÁREA DISPONIBILIZADA PARA PRESTAÇÃO DE SERVIÇOS DE INSPEÇÃO DE BAGAGENS.',
    objeto: 'Área destinada para realização de atividade de prestação de serviços de inspeção de bagagens despachadas Internacionais e Domésticas dos Terminais 1,2 e 3 às companhias aéreas e manuseio de bagagens nos sistemas de inspeção com o objetivo de atender as exigências do sistema de proteção da Aviação Civil e DAVSEC nº 04-21.; ÁREA DISPONIBILIZADA PARA PRESTAÇÃO DE SERVIÇOS DE INSPEÇÃO DE BAGAGENS.',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Terminais 1, 2 e 3 - Sistema BHS',
    gestorResponsavel: 'Gerência de Segurança AVSEC',
    emailContato: 'avsec.inspecao@orbital.com.br',
    telefoneContato: '(11) 2445-3344',
    dataInicio: '01/09/2020',
    dataTermino: '30/06/2027',
    vigenciaInicio: '2020-09-01',
    vigenciaFim: '2027-06-30',
    statusVigencia: 'Vigente',
    statusDocumentos: 'Validado',
    status: 'ATIVO',
    limiteBloqueioConformidade: 85,
    documentosContrato: [
      { id: 'doc-1409-1', nome: 'Homologação DAVSEC nº 04-21', tipo: 'Regulatório/AVSEC', status: 'Validado' },
      { id: 'doc-1409-2', nome: 'PGR / PCMSO / LTCAT Radioproteção', tipo: 'SST', status: 'Validado' },
      { id: 'doc-1409-3', nome: 'Certificado de Calibração Equipamentos Raio-X', tipo: 'Técnico', status: 'Validado' },
      { id: 'doc-1409-4', nome: 'Apólice Global de Seguros Aeroportuários', tipo: 'Seguros', status: 'Validado' },
    ],
  },
  {
    id: 'ctr-GRU020320180071',
    numero: 'GRU020320180071',
    titulo: 'CESSÃO DE ÁREA DESTINADA À CARGA E DESCARGA DE AERONAVES E INSTALAÇÃO DE ESCRITÓRIO ADMINISTRATIVO',
    objeto: 'CESSÃO DE ÁREA DESTINADA À CARGA E DESCARGA DE AERONAVES E INSTALAÇÃO DE ESCRITÓRIO ADMINISTRATIVO',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESCRITÓRIO',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Pátio 1 e Edifício Anexo',
    gestorResponsavel: 'Supervisão de Rampa',
    dataInicio: '01/10/2020',
    dataTermino: '30/09/2021',
    vigenciaInicio: '2020-10-01',
    vigenciaFim: '2021-09-30',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
  },
  {
    id: 'ctr-GRU020320180092',
    numero: 'GRU020320180092',
    titulo: 'ÁREA DESTINADA A ESCRITÓRIO OPERACIONAL',
    objeto: 'ÁREA DESTINADA A ESCRITÓRIO OPERACIONAL',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Edifício Terminal de Passageiros',
    gestorResponsavel: 'Gestão Predial',
    dataInicio: '16/10/2018',
    dataTermino: '15/10/2021',
    vigenciaInicio: '2018-10-16',
    vigenciaFim: '2021-10-15',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
  },
  {
    id: 'ctr-GRU020320180129',
    numero: 'GRU020320180129',
    titulo: 'ÁREA DESTINADA A VESTIÁRIO FEMININO E MASCULINO',
    objeto: 'ÁREA DESTINADA A VESTIÁRIO FEMININO E MASCULINO',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Subsolo Operacional T2',
    gestorResponsavel: 'Facilities & Infraestrutura',
    dataInicio: '01/12/2018',
    dataTermino: '30/11/2021',
    vigenciaInicio: '2018-12-01',
    vigenciaFim: '2021-11-30',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
  },
  {
    id: 'ctr-GRU020320170050',
    numero: 'GRU020320170050',
    titulo: 'ÁREA DESTINADA PARA REALIZAÇÃO DA ATIVIDADE DE PRESTAÇÃO DE SERVIÇOS DE INSPEÇÃO DE BAGAGENS DESPACHADAS ÁS COMPANHIAS AÉREAS E MANUSEIO DE BAGAGENS NOS SISTEMAS DE INSPEÇÃO',
    objeto: 'ÁREA DESTINADA PARA REALIZAÇÃO DA ATIVIDADE DE PRESTAÇÃO DE SERVIÇOS DE INSPEÇÃO DE BAGAGENS DESPACHADAS ÁS COMPANHIAS AÉREAS E MANUSEIO DE BAGAGENS NOS SISTEMAS DE INSPEÇÃO',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Terminal 2 e Terminal 3',
    gestorResponsavel: 'Coordenação de Operações AVSEC',
    emailContato: 'operacoes.inspecao@orbital.com.br',
    telefoneContato: '(11) 2445-9988',
    dataInicio: '01/09/2020',
    dataTermino: '30/06/2027',
    vigenciaInicio: '2020-09-01',
    vigenciaFim: '2027-06-30',
    statusVigencia: 'Vigente',
    statusDocumentos: 'Reprovado',
    status: 'ALERTA',
    limiteBloqueioConformidade: 85,
    observacoes: 'Pendência: Apólice de Seguro com cobertura insuficiente e Certidão Negativa Estadual vencida.',
    documentosContrato: [
      { id: 'doc-50-1', nome: 'Homologação AVSEC / ANAC', tipo: 'Regulatório', status: 'Validado' },
      { id: 'doc-50-2', nome: 'Apólice de Seguro de Responsabilidade Civil Aeroportuária', tipo: 'Seguros', status: 'Reprovado', motivoReprovacao: 'Valor da apólice abaixo do limite mínimo exigido em cláusula 8.2 do contrato.' },
      { id: 'doc-50-3', nome: 'Certidão Negativa de Débitos Estaduais (CND)', tipo: 'Fiscal', status: 'Reprovado', motivoReprovacao: 'Certidão vencida em 10/08/2026. Necessário emissão de nova via atualizada.' },
      { id: 'doc-50-4', nome: 'PGR e PCMSO da Equipe de Operações', tipo: 'SST', status: 'Validado' },
    ],
  },
  {
    id: 'ctr-GRU020320190023',
    numero: 'GRU020320190023',
    titulo: 'Área destinada a atividades administrativas e serviços de treinamento próprio e terceiros.',
    objeto: 'Área destinada a atividades administrativas e serviços de treinamento próprio e terceiros.',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Centro de Treinamento e Desenvolvimento',
    gestorResponsavel: 'Gerência de Treinamento e DHO',
    emailContato: 'treinamento@orbital.com.br',
    telefoneContato: '(11) 2445-5566',
    dataInicio: '01/07/2019',
    dataTermino: '30/06/2029',
    vigenciaInicio: '2019-07-01',
    vigenciaFim: '2029-06-30',
    statusVigencia: 'Vigente',
    statusDocumentos: 'Reprovado',
    status: 'ALERTA',
    limiteBloqueioConformidade: 85,
    observacoes: 'Pendência: Laudo AVCB do Centro de Treinamento em processo de renovação junto ao Corpo de Bombeiros.',
    documentosContrato: [
      { id: 'doc-23-1', nome: 'Contrato Social Consolidado', tipo: 'Jurídico', status: 'Validado' },
      { id: 'doc-23-2', nome: 'Auto de Vistoria do Corpo de Bombeiros (AVCB)', tipo: 'Predial/Segurança', status: 'Reprovado', motivoReprovacao: 'Protocolo de renovação do AVCB não aceito sem laudo provisório de vistoria.' },
      { id: 'doc-23-3', nome: 'Certificado de Credenciamento do Centro de Instrução ANAC', tipo: 'Regulatório', status: 'Validado' },
    ],
  },
  {
    id: 'ctr-GRU020320200026',
    numero: 'GRU020320200026',
    titulo: 'Área destinada a escritório operacional',
    objeto: 'Área destinada a escritório operacional',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    categoria: 'ESATA',
    cliente: 'GRU Airport - Concessionária',
    unidade: 'Terminal 1',
    gestorResponsavel: 'Supervisão de Turno',
    dataInicio: '01/02/2020',
    dataTermino: '31/01/2022',
    vigenciaInicio: '2020-02-01',
    vigenciaFim: '2022-01-31',
    statusVigencia: 'Vencido',
    statusDocumentos: 'Validado',
    status: 'ENCERRADO',
    limiteBloqueioConformidade: 85,
  },
  {
    id: 'ctr-01',
    numero: 'CTR-GPA-2026/01',
    titulo: 'Operação Logística, Armazenagem e Carga',
    objeto: 'Operação Logística, Armazenagem e Carga',
    cnpjPrestador: '05.007.113/0001-32',
    empresaPrestador: 'ORBITAL SERV. AUX. DE TRANSP. AÉREO',
    cliente: 'GPA - Centros de Distribuição',
    unidade: 'CD Osasco e CD Duque de Caxias',
    gestorResponsavel: 'Ricardo Fontes Silveira',
    emailContato: 'ricardo.fontes@gpa.com.br',
    telefoneContato: '(11) 98765-4321',
    areaId: 'area-01',
    areaNome: 'Logística & Centros de Distribuição (CDs)',
    dataInicio: '01/01/2026',
    dataTermino: '01/01/2027',
    vigenciaInicio: '2026-01-01',
    vigenciaFim: '2027-01-01',
    statusVigencia: 'Vigente',
    statusDocumentos: 'Validado',
    status: 'ATIVO',
    limiteBloqueioConformidade: 85,
    observacoes: 'Exige conformidade com ASO, EPI e Ordem de Serviço para entrada de operadores.',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-01',
    nome: 'Carlos Eduardo Silva',
    matricula: 'GPA-10492',
    cpf: '124.892.457-10',
    cargo: 'Operador de Empilhadeira',
    setor: 'Logística',
    areaId: 'area-01',
    areaNome: 'Logística & Centros de Distribuição (CDs)',
    areaResponsavelNome: 'Ricardo Fontes Silveira',
    areaResponsavelEmail: 'ricardo.fontes@gpa.com.br',
    areaResponsavelTelefone: '(11) 98765-4321',
    empresa: 'TransLog Logística Integrada',
    contratoId: 'ctr-01',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística e Carga',
    statusGeral: 'CRITICO',
    indicadorPercentual: 50,
    resumoGeral: 'Treinamento de Radioproteção/Operação VENCIDO e Ficha de EPI Pendente de assinatura. Risco na operação.',
    dataCadastro: '2026-07-10',
    dataUltimaLeitura: '2026-08-20',
    pendencias: [
      {
        id: 'p-01-1',
        tipo: 'TREINAMENTO_RADIOPROTECAO',
        nomeDocumento: 'Treinamento / Certificação Técnica Obrigatória',
        status: 'VENCIDO',
        dataEmissao: '2024-08-01',
        dataVencimento: '2026-08-01',
        diasRestantes: -21,
        observacoes: 'Reciclagem obrigatória vencida. Necessário novo certificado para autorizar operação.',
        obrigatorio: true,
        ultimaAtualizacao: '2026-08-20',
      },
      {
        id: 'p-01-2',
        tipo: 'FICHA_EPI',
        nomeDocumento: 'Ficha de EPI (NR-06)',
        status: 'PENDENTE',
        observacoes: 'Falta registro e assinatura da entrega de botina com biqueira e colete refletivo.',
        obrigatorio: true,
        ultimaAtualizacao: '2026-08-20',
      },
      {
        id: 'p-01-3',
        tipo: 'ORDEM_DE_SERVICO',
        nomeDocumento: 'Ordem de Serviço (NR-01)',
        status: 'EM_DIA',
        dataEmissao: '2026-01-15',
        dataVencimento: '2027-01-15',
        diasRestantes: 146,
        obrigatorio: true,
      },
      {
        id: 'p-01-4',
        tipo: 'ATESTADO_SAUDE_OCUPACIONAL',
        nomeDocumento: 'ASO Ocupacional (NR-07)',
        status: 'A_VENCER',
        dataEmissao: '2025-09-10',
        dataVencimento: '2026-09-10',
        diasRestantes: 19,
        observacoes: 'Vence em 19 dias (dentro do prazo de alerta de 30 dias). Agendar exame periódico.',
        obrigatorio: true,
      },
    ],
  },
  {
    id: 'emp-02',
    nome: 'Juliana Mendes Rocha',
    matricula: 'GPA-22019',
    cpf: '235.109.843-22',
    cargo: 'Eletricista de Manutenção Predial',
    setor: 'Manutenção',
    areaId: 'area-02',
    areaNome: 'Manutenção Predial & Obras',
    areaResponsavelNome: 'Mariana Duarte Prado',
    areaResponsavelEmail: 'mariana.prado@gpa.com.br',
    areaResponsavelTelefone: '(11) 97654-1122',
    empresa: 'ServTec Manutenção & Obras',
    contratoId: 'ctr-02',
    contratoNome: 'CTR-GPA-2026/04 - Manutenção Elétrica e Refrigeração',
    statusGeral: 'EM_DIA',
    indicadorPercentual: 100,
    resumoGeral: 'Todos os 4 pilares de conformidade 100% atualizados.',
    dataCadastro: '2026-06-01',
    dataUltimaLeitura: '2026-08-15',
    pendencias: [
      {
        id: 'p-02-1',
        tipo: 'ORDEM_DE_SERVICO',
        nomeDocumento: 'Ordem de Serviço (NR-01)',
        status: 'EM_DIA',
        dataEmissao: '2026-02-10',
        dataVencimento: '2027-02-10',
        diasRestantes: 172,
        obrigatorio: true,
      },
      {
        id: 'p-02-2',
        tipo: 'ATESTADO_SAUDE_OCUPACIONAL',
        nomeDocumento: 'ASO Ocupacional (NR-07)',
        status: 'EM_DIA',
        dataEmissao: '2026-03-01',
        dataVencimento: '2027-03-01',
        diasRestantes: 191,
        obrigatorio: true,
      },
      {
        id: 'p-02-3',
        tipo: 'FICHA_EPI',
        nomeDocumento: 'Ficha de EPI (NR-06)',
        status: 'EM_DIA',
        dataEmissao: '2026-02-15',
        dataVencimento: '2027-02-15',
        diasRestantes: 177,
        obrigatorio: true,
      },
      {
        id: 'p-02-4',
        tipo: 'TREINAMENTO_RADIOPROTECAO',
        nomeDocumento: 'Certificado NR-10 e Treinamento Técnico',
        status: 'EM_DIA',
        dataEmissao: '2025-11-20',
        dataVencimento: '2027-11-20',
        diasRestantes: 455,
        obrigatorio: true,
      },
    ],
  },
  {
    id: 'emp-03',
    nome: 'Rodrigo Lima Martins',
    matricula: 'GPA-55102',
    cpf: '381.762.901-44',
    cargo: 'Vigilante Patrimonial',
    setor: 'Segurança',
    areaId: 'area-03',
    areaNome: 'Prevenção de Perdas & Segurança Patrimonial',
    areaResponsavelNome: 'Carlos Alberto Tavares',
    areaResponsavelEmail: 'carlos.tavares@gpa.com.br',
    areaResponsavelTelefone: '(11) 99882-3344',
    empresa: 'Protec Segurança e Vigilância',
    contratoId: 'ctr-03',
    contratoNome: 'CTR-GPA-2026/08 - Segurança Patrimonial e Portaria',
    statusGeral: 'BLOQUEADO',
    indicadorPercentual: 25,
    resumoGeral: 'ASO Vencido há mais de 40 dias e Ordem de Serviço Pendente. Bloqueado na portaria.',
    dataCadastro: '2026-05-12',
    dataUltimaLeitura: '2026-08-18',
    pendencias: [
      {
        id: 'p-03-1',
        tipo: 'ORDEM_DE_SERVICO',
        nomeDocumento: 'Ordem de Serviço (NR-01)',
        status: 'PENDENTE',
        observacoes: 'Aguardando termo de ciência e integração assinado.',
        obrigatorio: true,
      },
      {
        id: 'p-03-2',
        tipo: 'ATESTADO_SAUDE_OCUPACIONAL',
        nomeDocumento: 'ASO Ocupacional (NR-07)',
        status: 'VENCIDO',
        dataEmissao: '2025-07-12',
        dataVencimento: '2026-07-12',
        diasRestantes: -41,
        observacoes: 'Exame periódico vencido em 12/07/2026. Acesso bloqueado.',
        obrigatorio: true,
      },
      {
        id: 'p-03-3',
        tipo: 'FICHA_EPI',
        nomeDocumento: 'Ficha de EPI (NR-06)',
        status: 'EM_DIA',
        dataEmissao: '2026-03-10',
        dataVencimento: '2027-03-10',
        diasRestantes: 200,
        obrigatorio: true,
      },
      {
        id: 'p-03-4',
        tipo: 'TREINAMENTO_RADIOPROTECAO',
        nomeDocumento: 'Reciclagem de Formação de Vigilante',
        status: 'VENCIDO',
        dataEmissao: '2024-06-30',
        dataVencimento: '2026-06-30',
        diasRestantes: -53,
        observacoes: 'Reciclagem de segurança vencida na Polícia Federal.',
        obrigatorio: true,
      },
    ],
  },
  {
    id: 'emp-04',
    nome: 'Amanda Ferreira Costa',
    matricula: 'GPA-33180',
    cpf: '452.980.312-55',
    cargo: 'Auxiliar de Limpeza Técnica',
    setor: 'Facilities',
    areaId: 'area-04',
    areaNome: 'Facilities, Limpeza & Higienização',
    areaResponsavelNome: 'Juliana Beatriz Neves',
    areaResponsavelEmail: 'juliana.neves@gpa.com.br',
    areaResponsavelTelefone: '(11) 99123-5566',
    empresa: 'CleanFast Facilities',
    contratoId: 'ctr-04',
    contratoNome: 'CTR-GPA-2026/12 - Facilities e Higienização Técnica',
    statusGeral: 'PENDENTE',
    indicadorPercentual: 75,
    resumoGeral: 'ASO a vencer em 14 dias e Ficha de EPI Pendente de atualização.',
    dataCadastro: '2026-07-20',
    dataUltimaLeitura: '2026-08-19',
    pendencias: [
      {
        id: 'p-04-1',
        tipo: 'ORDEM_DE_SERVICO',
        nomeDocumento: 'Ordem de Serviço (NR-01)',
        status: 'EM_DIA',
        dataEmissao: '2026-04-01',
        dataVencimento: '2027-04-01',
        diasRestantes: 222,
        obrigatorio: true,
      },
      {
        id: 'p-04-2',
        tipo: 'ATESTADO_SAUDE_OCUPACIONAL',
        nomeDocumento: 'ASO Ocupacional (NR-07)',
        status: 'A_VENCER',
        dataEmissao: '2025-09-05',
        dataVencimento: '2026-09-05',
        diasRestantes: 14,
        observacoes: 'Vence em 14 dias. Agendado para próxima semana.',
        obrigatorio: true,
      },
      {
        id: 'p-04-3',
        tipo: 'FICHA_EPI',
        nomeDocumento: 'Ficha de EPI (NR-06)',
        status: 'PENDENTE',
        observacoes: 'Pendente assinatura de luvas de nitrila e óculos de proteção.',
        obrigatorio: true,
      },
      {
        id: 'p-04-4',
        tipo: 'TREINAMENTO_RADIOPROTECAO',
        nomeDocumento: 'Treinamento de Produtos Químicos e Higienização',
        status: 'EM_DIA',
        dataEmissao: '2026-04-10',
        dataVencimento: '2027-04-10',
        diasRestantes: 231,
        obrigatorio: true,
      },
    ],
  },
];

export const INITIAL_DEMAND_LOGS: DemandLog[] = [
  {
    id: 'log-01',
    funcionarioId: 'emp-01',
    funcionarioNome: 'Carlos Eduardo Silva',
    areaId: 'area-01',
    areaNome: 'Logística & Centros de Distribuição (CDs)',
    responsavelArea: 'Ricardo Fontes Silveira',
    contratoId: 'ctr-01',
    contratoNome: 'CTR-GPA-2026/01',
    canal: 'whatsapp',
    destinatario: '(11) 98765-4321',
    dataEnvio: '2026-08-20 14:30',
    prazoResolucao: '2026-08-25',
    status: 'ENVIADO',
    pendenciasCobradas: [
      'Certificado de Treinamento Técnico (VENCIDO)',
      'Ficha de EPI (PENDENTE)',
    ],
    mensagemTexto: `*NOTIFICAÇÃO DE REGULARIZAÇÃO DE CONTRATOS - GPA*
Olá Gestor Ricardo Fontes, informamos que o colaborador *Carlos Eduardo Silva* (Matrícula: GPA-10492) possui itens vencidos e a vencer no CD Osasco.
Prazo limite para regularização: 25/08/2026.`,
  },
];

export const SAMPLE_OCR_IMAGES = {
  print1: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="340" fill="%23ffffff"><rect width="100%" height="100%" fill="%23f8fafc"/><rect x="20" y="20" width="560" height="40" rx="8" fill="%23006837"/><text x="40" y="46" fill="%23ffffff" font-size="15" font-weight="bold" font-family="sans-serif">SISTEMA GPA - CONSULTA DE CONFORMIDADE DE CONTRATOS</text><rect x="20" y="75" width="560" height="90" rx="8" fill="%23ffffff" stroke="%23cbd5e1"/><text x="40" y="105" fill="%230f172a" font-size="14" font-weight="bold" font-family="sans-serif">NOME: CARLOS EDUARDO SILVA</text><text x="40" y="125" fill="%23475569" font-size="12" font-family="sans-serif">MATRICULA: GPA-10492 | CARGO: OPERADOR DE EMPILHADEIRA</text><text x="40" y="145" fill="%23475569" font-size="12" font-family="sans-serif">AREA: LOGISTICA &amp; CDS | CONTRATO: CTR-GPA-2026/01</text><rect x="20" y="180" width="560" height="135" rx="8" fill="%23ffffff" stroke="%23cbd5e1"/><text x="40" y="205" fill="%230f172a" font-size="13" font-weight="bold" font-family="sans-serif">DOCUMENTOS OBRIGATORIOS DE SST &amp; CONTRATO:</text><text x="40" y="230" fill="%23b45309" font-size="12" font-family="sans-serif">1. [PENDENTE] Ordem de Servico NR-01</text><text x="40" y="250" fill="%23d97706" font-size="12" font-family="sans-serif">2. [A VENCER - 19 DIAS] ASO Ocupacional - Venc: 10/09/2026</text><text x="40" y="270" fill="%2315803d" font-size="12" font-family="sans-serif">3. [EM DIA] Ficha de EPI - Assinada</text><text x="40" y="290" fill="%23b91c1c" font-size="12" font-family="sans-serif">4. [VENCIDO] Certificacao Tecnica Obrigatoria - Venc: 01/08/2026</text></svg>',
  print2: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="340" fill="%23ffffff"><rect width="100%" height="100%" fill="%23f8fafc"/><rect x="20" y="20" width="560" height="40" rx="8" fill="%23006837"/><text x="40" y="46" fill="%23ffffff" font-size="15" font-weight="bold" font-family="sans-serif">SISTEMA GPA - CONSULTA DE CONFORMIDADE DE CONTRATOS</text><rect x="20" y="75" width="560" height="90" rx="8" fill="%23ffffff" stroke="%23cbd5e1"/><text x="40" y="105" fill="%230f172a" font-size="14" font-weight="bold" font-family="sans-serif">NOME: JULIANA MENDES ROCHA</text><text x="40" y="125" fill="%23475569" font-size="12" font-family="sans-serif">MATRICULA: GPA-22019 | CARGO: ELETRICISTA DE MANUTENCAO</text><text x="40" y="145" fill="%23475569" font-size="12" font-family="sans-serif">AREA: MANUTENCAO PREDIAL | STATUS: 100% EM DIA</text><rect x="20" y="180" width="560" height="135" rx="8" fill="%23ffffff" stroke="%23cbd5e1"/><text x="40" y="205" fill="%230f172a" font-size="13" font-weight="bold" font-family="sans-serif">DOCUMENTOS OBRIGATORIOS:</text><text x="40" y="230" fill="%2315803d" font-size="12" font-family="sans-serif">1. [EM DIA] Ordem de Servico NR-01</text><text x="40" y="250" fill="%2315803d" font-size="12" font-family="sans-serif">2. [EM DIA] ASO Ocupacional - Validade: 01/03/2027</text><text x="40" y="270" fill="%2315803d" font-size="12" font-family="sans-serif">3. [EM DIA] Ficha de EPI - Assinada</text><text x="40" y="290" fill="%2315803d" font-size="12" font-family="sans-serif">4. [EM DIA] Certificado NR-10 e Seguranca - Validade: 20/11/2027</text></svg>',
  print3: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="340" fill="%23ffffff"><rect width="100%" height="100%" fill="%23f8fafc"/><rect x="20" y="20" width="560" height="40" rx="8" fill="%23991b1b"/><text x="40" y="46" fill="%23ffffff" font-size="15" font-weight="bold" font-family="sans-serif">ALERTA GPA - BLOQUEIO DE ACESSO IMINENTE</text><rect x="20" y="75" width="560" height="90" rx="8" fill="%23ffffff" stroke="%23fca5a5"/><text x="40" y="105" fill="%230f172a" font-size="14" font-weight="bold" font-family="sans-serif">NOME: RODRIGO LIMA MARTINS</text><text x="40" y="125" fill="%23475569" font-size="12" font-family="sans-serif">MATRICULA: GPA-55102 | CARGO: VIGILANTE PATRIMONIAL</text><text x="40" y="145" fill="%23b91c1c" font-size="12" font-weight="bold" font-family="sans-serif">AREA: SEGURANCA | STATUS: BLOQUEADO (25%)</text><rect x="20" y="180" width="560" height="135" rx="8" fill="%23ffffff" stroke="%23fca5a5"/><text x="40" y="205" fill="%230f172a" font-size="13" font-weight="bold" font-family="sans-serif">SITUACAO DOS DOCUMENTOS:</text><text x="40" y="230" fill="%23b45309" font-size="12" font-family="sans-serif">1. [PENDENTE] Ordem de Servico NR-01</text><text x="40" y="250" fill="%23b91c1c" font-size="12" font-weight="bold" font-family="sans-serif">2. [VENCIDO] ASO Periodico Vencido em 12/07/2026</text><text x="40" y="270" fill="%2315803d" font-size="12" font-family="sans-serif">3. [EM DIA] Ficha de EPI Atualizada</text><text x="40" y="290" fill="%23b91c1c" font-size="12" font-weight="bold" font-family="sans-serif">4. [VENCIDO] Reciclagem de Seguranca Vencida</text></svg>',
};

export const SAMPLE_OCR_RESULTS: Record<string, Partial<Employee>> = {
  print1: {
    nome: 'Carlos Eduardo Silva',
    matricula: 'GPA-10492',
    cargo: 'Operador de Empilhadeira',
    setor: 'Logística & CDs',
    areaId: 'area-01',
    areaNome: 'Logística & Centros de Distribuição (CDs)',
    empresa: 'TransLog Logística Integrada',
    indicadorPercentual: 50,
    statusGeral: 'CRITICO',
    resumoGeral: 'Pendente Ordem de Serviço NR-01 e Certificação Vencida.',
    pendencias: [
      {
        id: 'p_s1_1',
        tipo: 'ORDEM_DE_SERVICO',
        nomeDocumento: 'Ordem de Serviço (NR-01)',
        status: 'PENDENTE',
        obrigatorio: true,
        observacoes: 'Aguardando assinatura do colaborador.',
      },
      {
        id: 'p_s1_2',
        tipo: 'ATESTADO_SAUDE_OCUPACIONAL',
        nomeDocumento: 'ASO Ocupacional (NR-07)',
        status: 'A_VENCER',
        dataVencimento: '2026-09-10',
        diasRestantes: 19,
        obrigatorio: true,
      },
      {
        id: 'p_s1_3',
        tipo: 'FICHA_EPI',
        nomeDocumento: 'Ficha de EPI (NR-06)',
        status: 'EM_DIA',
        obrigatorio: true,
      },
      {
        id: 'p_s1_4',
        tipo: 'TREINAMENTO_RADIOPROTECAO',
        nomeDocumento: 'Certificação Técnica Obrigatória',
        status: 'VENCIDO',
        dataVencimento: '2026-08-01',
        diasRestantes: -21,
        obrigatorio: true,
        observacoes: 'Reciclagem obrigatória pendente.',
      },
    ],
  },
  print2: {
    nome: 'Juliana Mendes Rocha',
    matricula: 'GPA-22019',
    cargo: 'Eletricista de Manutenção Predial',
    setor: 'Manutenção',
    areaId: 'area-02',
    areaNome: 'Manutenção Predial & Obras',
    empresa: 'ServTec Manutenção & Obras',
    indicadorPercentual: 100,
    statusGeral: 'EM_DIA',
    resumoGeral: 'Todos os documentos e certificados em conformidade com as normas regulamentadoras.',
    pendencias: [
      {
        id: 'p_s2_1',
        tipo: 'ORDEM_DE_SERVICO',
        nomeDocumento: 'Ordem de Serviço (NR-01)',
        status: 'EM_DIA',
        obrigatorio: true,
      },
      {
        id: 'p_s2_2',
        tipo: 'ATESTADO_SAUDE_OCUPACIONAL',
        nomeDocumento: 'ASO Ocupacional (NR-07)',
        status: 'EM_DIA',
        dataVencimento: '2027-03-01',
        diasRestantes: 191,
        obrigatorio: true,
      },
      {
        id: 'p_s2_3',
        tipo: 'FICHA_EPI',
        nomeDocumento: 'Ficha de EPI (NR-06)',
        status: 'EM_DIA',
        obrigatorio: true,
      },
      {
        id: 'p_s2_4',
        tipo: 'TREINAMENTO_RADIOPROTECAO',
        nomeDocumento: 'Certificado NR-10 e Segurança',
        status: 'EM_DIA',
        dataVencimento: '2027-11-20',
        diasRestantes: 455,
        obrigatorio: true,
      },
    ],
  },
  print3: {
    nome: 'Rodrigo Lima Martins',
    matricula: 'GPA-55102',
    cargo: 'Vigilante Patrimonial',
    setor: 'Segurança',
    areaId: 'area-03',
    areaNome: 'Prevenção de Perdas & Segurança Patrimonial',
    empresa: 'Protec Segurança e Vigilância',
    indicadorPercentual: 25,
    statusGeral: 'BLOQUEADO',
    resumoGeral: 'Colaborador com ASO e Reciclagem vencidos. Acesso bloqueado em portaria.',
    pendencias: [
      {
        id: 'p_s3_1',
        tipo: 'ORDEM_DE_SERVICO',
        nomeDocumento: 'Ordem de Serviço (NR-01)',
        status: 'PENDENTE',
        obrigatorio: true,
      },
      {
        id: 'p_s3_2',
        tipo: 'ATESTADO_SAUDE_OCUPACIONAL',
        nomeDocumento: 'ASO Ocupacional (NR-07)',
        status: 'VENCIDO',
        dataVencimento: '2026-07-12',
        diasRestantes: -41,
        obrigatorio: true,
        observacoes: 'Exame periódico vencido há mais de 30 dias.',
      },
      {
        id: 'p_s3_3',
        tipo: 'FICHA_EPI',
        nomeDocumento: 'Ficha de EPI (NR-06)',
        status: 'EM_DIA',
        obrigatorio: true,
      },
      {
        id: 'p_s3_4',
        tipo: 'TREINAMENTO_RADIOPROTECAO',
        nomeDocumento: 'Reciclagem de Formação de Vigilante',
        status: 'VENCIDO',
        dataVencimento: '2026-06-30',
        diasRestantes: -53,
        obrigatorio: true,
      },
    ],
  },
};

export const INITIAL_TRABALHISTA_ENVIOS: TrabalhistaEnvio[] = [
  {
    id: 'trab-env-01',
    mes: '06',
    mesNome: 'Junho',
    ano: 2026,
    dataEnvio: '27/07/2026 12:14:48',
    status: 'Validado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    documentosAnexados: ['Folha de Pagamento 06/2026', 'Guia FGTS + Comprovante', 'GPS / Previdência', 'Comprovantes de Salário'],
    observacoes: 'Documentação mensal completa e validada sem ressalvas.',
    validadoPor: 'Auditoria Trabalhista GPA',
    dataValidacao: '28/07/2026 09:30:15',
  },
  {
    id: 'trab-env-02',
    mes: '05',
    mesNome: 'Maio',
    ano: 2026,
    dataEnvio: '24/06/2026 12:06:07',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Falta do comprovante bancário da GFIP de 3 colaboradores.',
    documentosAnexados: ['Folha de Pagamento 05/2026', 'GFIP'],
    observacoes: 'Arquivo parcial rejeitado pela auditoria.',
  },
  {
    id: 'trab-env-03',
    mes: '05',
    mesNome: 'Maio',
    ano: 2026,
    dataEnvio: '07/07/2026 08:51:16',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Guia do FGTS sem autenticação mecânica legível.',
    documentosAnexados: ['Folha de Pagamento', 'Comprovante Bancário'],
  },
  {
    id: 'trab-env-04',
    mes: '05',
    mesNome: 'Maio',
    ano: 2026,
    dataEnvio: '13/07/2026 11:28:12',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Divergência entre o total de funcionários na folha e na GFIP.',
    documentosAnexados: ['Folha Retificada 05/2026', 'GFIP'],
  },
  {
    id: 'trab-env-05',
    mes: '05',
    mesNome: 'Maio',
    ano: 2026,
    dataEnvio: '14/07/2026 09:04:38',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Comprovante de pagamento de VT e VR não anexado.',
    documentosAnexados: ['Folha 05/2026', 'Guia FGTS Autenticada'],
  },
  {
    id: 'trab-env-06',
    mes: '05',
    mesNome: 'Maio',
    ano: 2026,
    dataEnvio: '15/07/2026 17:11:30',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Certidão CNDT vencida anexada no lote.',
    documentosAnexados: ['Folha', 'FGTS', 'Comprovantes Bancários'],
  },
  {
    id: 'trab-env-07',
    mes: '05',
    mesNome: 'Maio',
    ano: 2026,
    dataEnvio: '16/07/2026 11:11:12',
    status: 'Validado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    documentosAnexados: ['Folha 05/2026 Completa', 'FGTS Pago', 'CNDT Atualizada', 'Comprovantes Salariais', 'Recibos Benefícios'],
    observacoes: 'Todas as pendências do mês 05 foram sanadas e validadas pela auditoria.',
    validadoPor: 'Auditoria Trabalhista GPA',
    dataValidacao: '16/07/2026 16:45:00',
  },
  {
    id: 'trab-env-08',
    mes: '04',
    mesNome: 'Abril',
    ano: 2026,
    dataEnvio: '26/06/2026 12:39:23',
    status: 'Validado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    documentosAnexados: ['Folha 04/2026', 'FGTS', 'INSS', 'Recibos Salariais'],
    observacoes: 'Envio retificador aprovado integralmente.',
    validadoPor: 'Auditoria Trabalhista GPA',
  },
  {
    id: 'trab-env-09',
    mes: '04',
    mesNome: 'Abril',
    ano: 2026,
    dataEnvio: '26/05/2026 11:37:21',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Guia de previdência social sem recibo de transmissão.',
  },
  {
    id: 'trab-env-10',
    mes: '04',
    mesNome: 'Abril',
    ano: 2026,
    dataEnvio: '03/06/2026 14:41:59',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Assinatura digital inválida no relatório da folha.',
  },
  {
    id: 'trab-env-11',
    mes: '04',
    mesNome: 'Abril',
    ano: 2026,
    dataEnvio: '09/06/2026 17:46:57',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Extrato analítico do FGTS incompleto.',
  },
  {
    id: 'trab-env-12',
    mes: '04',
    mesNome: 'Abril',
    ano: 2026,
    dataEnvio: '24/06/2026 11:50:29',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Falta do comprovante de repasse sindical.',
  },
  {
    id: 'trab-env-13',
    mes: '03',
    mesNome: 'Março',
    ano: 2026,
    dataEnvio: '24/04/2026 15:26:07',
    status: 'Reprovado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    motivoReprovacao: 'Recibo salarial de 1 colaborador não assinado.',
  },
  {
    id: 'trab-env-14',
    mes: '03',
    mesNome: 'Março',
    ano: 2026,
    dataEnvio: '05/05/2026 14:34:33',
    status: 'Validado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    documentosAnexados: ['Folha 03/2026', 'FGTS', 'INSS', 'Recibos'],
    observacoes: 'Validação concluída com êxito.',
    validadoPor: 'Auditoria Trabalhista GPA',
  },
  {
    id: 'trab-env-15',
    mes: '02',
    mesNome: 'Fevereiro',
    ano: 2026,
    dataEnvio: '25/03/2026 10:02:04',
    status: 'Validado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    documentosAnexados: ['Folha 02/2026', 'FGTS', 'INSS'],
    observacoes: 'Primeiro lote validado.',
    validadoPor: 'Auditoria Trabalhista GPA',
  },
  {
    id: 'trab-env-16',
    mes: '02',
    mesNome: 'Fevereiro',
    ano: 2026,
    dataEnvio: '07/04/2026 16:23:15',
    status: 'Validado',
    contratoNome: 'CTR-GPA-2026/01 - Operação Logística',
    empresa: 'WFS Serviços Aeroportuários e Logística',
    documentosAnexados: ['Recibo Complementar 02/2026', 'Certidões'],
    observacoes: 'Complemento de auditoria validado.',
    validadoPor: 'Auditoria Trabalhista GPA',
  },
];

