import { AbastecimentoRecord } from '../types';

export const INITIAL_RECORDS: AbastecimentoRecord[] = [
  {
    id: 'rec-1',
    numero: '2293305',
    formaPagamento: 'CONTRATO',
    cliente: 'ORBITAL SERV AUX TRANSP AEREO',
    horaChegada: '07:13',
    inicioAbastecimento: '07:14',
    terminoAbastecimento: '07:22',
    produto: 'DIESEL',
    volume: '224,00',
    obs: 'GE135 - PÁTIO T2',
    assinaturaCliente: 'joanilson 304371',
    fileName: 'OS_2293305_GE135.jpg',
    dataCriacao: new Date(Date.now() - 3600000 * 5).toISOString(),
    statusEnvio: 'enviado_drive',
    driveFileId: '1AbC_sample_drive_id_99x',
    driveFileUrl: 'https://drive.google.com/drive/folders/',
    statusMsg: 'Salvo com sucesso no Drive',
  },
  {
    id: 'rec-2',
    numero: '2293306',
    formaPagamento: 'CONTRATO',
    cliente: 'ORBITAL SERV AUX TRANSP AEREO',
    horaChegada: '08:45',
    inicioAbastecimento: '08:50',
    terminoAbastecimento: '08:58',
    produto: 'DIESEL',
    volume: '180,50',
    obs: 'GE140 - PÁTIO T3',
    assinaturaCliente: 'joanilson 304371',
    fileName: 'OS_2293306_GE140.jpg',
    dataCriacao: new Date(Date.now() - 3600000 * 4).toISOString(),
    statusEnvio: 'enviado_drive',
    driveFileId: '1AbD_sample_drive_id_88y',
    driveFileUrl: 'https://drive.google.com/drive/folders/',
    statusMsg: 'Salvo com sucesso no Drive',
  },
  {
    id: 'rec-3',
    numero: '2293310',
    formaPagamento: 'FATURADO',
    cliente: 'SWISSPORT BRASIL LTDA',
    horaChegada: '10:15',
    inicioAbastecimento: '10:20',
    terminoAbastecimento: '10:35',
    produto: 'JET A-1',
    volume: '1.450,00',
    obs: 'TRATOR T-04 / PR-GUZ',
    assinaturaCliente: 'marcos 441029',
    fileName: 'OS_2293310_SWISS.jpg',
    dataCriacao: new Date(Date.now() - 3600000 * 3).toISOString(),
    statusEnvio: 'enviado_drive',
    driveFileId: '1AbE_sample_drive_id_77z',
    driveFileUrl: 'https://drive.google.com/drive/folders/',
    statusMsg: 'Salvo com sucesso no Drive',
  },
  {
    id: 'rec-4',
    numero: '2293315',
    formaPagamento: 'CONTRATO',
    cliente: 'DNATA SERVICOS AUXILIARES',
    horaChegada: '11:30',
    inicioAbastecimento: '11:35',
    terminoAbastecimento: '11:48',
    produto: 'DIESEL S10',
    volume: '310,00',
    obs: 'REBOCADOR RB-09',
    assinaturaCliente: 'claudio 552190',
    fileName: 'OS_2293315_DNATA.jpg',
    dataCriacao: new Date(Date.now() - 3600000 * 2).toISOString(),
    statusEnvio: 'enviado_drive',
    driveFileId: '1AbF_sample_drive_id_66w',
    driveFileUrl: 'https://drive.google.com/drive/folders/',
    statusMsg: 'Salvo com sucesso no Drive',
  },
  {
    id: 'rec-5',
    numero: '2293322',
    formaPagamento: 'A VISTA',
    cliente: 'LATAM AIRLINES BRASIL',
    horaChegada: '13:05',
    inicioAbastecimento: '13:10',
    terminoAbastecimento: '13:28',
    produto: 'JET A-1',
    volume: '3.200,00',
    obs: 'GPU-08 / BOX 214',
    assinaturaCliente: 'rodrigo 881230',
    fileName: 'OS_2293322_LATAM.jpg',
    dataCriacao: new Date(Date.now() - 3600000).toISOString(),
    statusEnvio: 'enviado_drive',
    driveFileId: '1AbG_sample_drive_id_55v',
    driveFileUrl: 'https://drive.google.com/drive/folders/',
    statusMsg: 'Salvo com sucesso no Drive',
  },
  {
    id: 'rec-6',
    numero: '2293328',
    formaPagamento: 'CONTRATO',
    cliente: 'GOL LINHAS AEREAS',
    horaChegada: '14:20',
    inicioAbastecimento: '14:25',
    terminoAbastecimento: '14:38',
    produto: 'DIESEL',
    volume: '195,00',
    obs: 'ESCADA MOTORIZADA EM-03',
    assinaturaCliente: 'felipe 309481',
    fileName: 'OS_2293328_GOL.jpg',
    dataCriacao: new Date(Date.now() - 1800000).toISOString(),
    statusEnvio: 'enviado_drive',
    driveFileId: '1AbH_sample_drive_id_44u',
    driveFileUrl: 'https://drive.google.com/drive/folders/',
    statusMsg: 'Salvo com sucesso no Drive',
  },
];
